[package]
name = "markets-daemons"
version = "0.1.0"
authors = ["pavelpichrt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
